language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t frankdaza2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true frankdaza2/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-877403824238"
  bucket_path: "docker-react"
  on:
    branch: master
